### ISSUE TITLE
Mailtexte in SETTINGS-Datei auslagern

### ISSUE THREAD

**Issue by chriswars** [d120/pyofahrt#11]
Die Mailtexte sollten zentral in der Settings-Datei gespeichert werden und nicht wie bisher an der Stelle, an der die Mails ausgelöst werden. Jeweils mit Titel, Text, Sender und Empfängern

**Comment by exploide** [comment]
Wenn der default Sender wie in https://github.com/d120/pyophase/blob/master/pyophase/settings_production.py#L35 gesetzt ist und die Mails wie in https://github.com/d120/pyophase/blob/master/workshops/views.py#L36 versendet werden (sieht komplizierter aus als es sein muss, wegen Internationalisierung und Variablen, etc), kann auf die explizite Angabe einer Senderadresse verzichtet werden (wie es bei jedem Aufruf von `send_mail` nötig ist).
