### ISSUE TITLE
getrennte Formularseiten für Orga und Tutor

### ISSUE THREAD

**Issue by matedealer** [d120/pyofahrt#139]
Wenn es verschiedene Zeiträume zur Anmeldung gibt, wäre es vll. besser verschiedene Formularseiten bereit zustellen.

**Comment by pollti** [comment]
Ist hier wirklich pyOfahrt oder eventuell [pyOphase](https://github.com/d120/pyophase) gemeint?

**Comment by matedealer** [comment]
gnarff.. du hast ja Recht....
