### ISSUE TITLE
OFahrt Leitung kann Workshops anlegen aber nicht modifizieren

### ISSUE THREAD

**Issue by Iliricon** [d120/pyofahrt#15]
Jo, ziemlich genau das

**Comment by chriswars** [comment]
Kann ich nicht reproduzieren. Klappt sowohl im Adminbereich als auch über die Webseite selbst

**Comment by chriswars** [comment]
Okay ich nehme alles zurück: War ein Einstellungsfehler, kein Softwarefehler
