### ISSUE TITLE
Do not use weak PRNG for password generation

### ISSUE THREAD

**Issue by exploide** [d120/pyofahrt#16]
In `staff/admin.py`, `random.choice` is used to generate passwords for organizers and workshop tutors. Internally, this uses a weak pseudo random number generator which is not suitable for password generation and cryptographic purposes.

Instead, Python offers the more secure `SystemRandom` PRNG. Additionally, the upcoming Python 3.6 standard will probably introduce a more userfriendly `secrets` module. This will include proper functions for typical tasks concerning passwords and tokens.

In this case, it does not really matter since Django already ships with a suitable password generation functionality. Please consider using something like this:
```
password = User.objects.make_random_password()
```
See https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#django.contrib.auth.models.BaseUserManager.make_random_password

**Comment by exploide** [comment]
Isn't the function `randomword` and the usage of this in https://github.com/d120/pyofahrt/blob/254c1c1e0879bc20213883bfed771bfda83ac006/staff/admin.py#L32 unnecessary by now?

**Comment by chriswars** [comment]
Well... yeah. Cleaned up in 5aa4ad8bafffe18326c6b7635712f7b4c4eef5c9
