### ISSUE TITLE
Workshop-Zeitslots

### ISSUE THREAD

**Issue by BluemlJ** [d120/pyofahrt#20]
Es sollte möglich sein einem Workshop mehr als nur einen Zeitslot zuzuweisen.

**Comment by chriswars** [comment]
Ich glaube es wäre von der Modellierung her sinnvoller für jeden Slot einen eigenes Workshopobjekt anzulegen da die Instanzen ja einen konkreten Workshop repräsentieren und keine Workshop-Idee.

Was hälst du stattdessen von einem Button mit dem der Woskhoporga einen Workshop auf einen anderen Zeitslot rüberduplizieren kann?

**Comment by BluemlJ** [comment]
Ja, kann man so lösen
