### ISSUE TITLE
Neuen Wikiartikel erstellen

### ISSUE THREAD

**Issue by Atarust** [d120/pyofahrt#29]
Es sollte einen Button geben, mit dem man neue Wikiartikel erstellen kann.

**Comment by chriswars** [comment]
Neue Artikel sollten (wie im Trac) über Links dort hin entstehen oder direkt über die URL angelegt werden. Ist ein Button dafür wirklich nötig?

**Comment by Atarust** [comment]
Nö, Button nicht notwendig
