### ISSUE TITLE
Zimmerverteilung nach Geschlecht

### ISSUE THREAD

**Issue by Atarust** [d120/pyofahrt#4]
Es sollte eine Auswahl geben, ob man in einem 
* Männlichen Zimmer
* Weiblichen Zimmer
* Gemischten Zimmer
sein will.

**Comment by chriswars** [comment]
@Iliricon hierzu ist eine Entscheidung von uns notwendig

**Comment by chriswars** [comment]
-push-@Iliricon

**Comment by chriswars** [comment]
Pink fluffy unicorns waiting for an answer from @Iliricon

**Comment by Iliricon** [comment]
Keine Entscheidung, gemischtgeschlechtlich ist in einer Jhb einfach nicht drin, oder?

**Comment by chriswars** [comment]
So sei es!
