### ISSUE TITLE
Links die Login benoetigen sollten werfen Fehlermeldungen

### ISSUE THREAD

**Issue by X52p** [d120/pyofahrt#81]
Links die einen login benoetigen, wie z.B https://d120.de/ofahrt/workshops/create
sollten nach dem Login Fragen anstelle eine Fehlermeldung (not found) zu werfen und auf 
https://d120.de/de/staff/login/?next=/ofahrt/workshops/create
weiter zu leiten.

**Comment by Miterion** [comment]
Seems that the server has a problem with the trailing slash. The url `ofahrt/staff/login/?next=/ofahrt/workshops/`, does not work `ofahrt/staff/login?next=/ofahrt/workshops/` does.

**Comment by Miterion** [comment]
Fixed it with af10647
