### ISSUE TITLE
Preferred room partners should not be mandatory (for freshmen)

### ISSUE THREAD

**Issue by Miterion** [d120/pyofahrt#84]
Making the field "Gewünschte Zimmernachbarn" mandatory is a bad design decision. This forces freshmen to fill this field regardless of their specific wishes. Also in this implementation using a char field is neither sensible (this should be a text field) nor it is usuable in the long run, because the information has to be parsed manually.

**Comment by MaggiR** [comment]
The Ofahrt-Leitung decided to remove this option entirely from the application form.
